services:
  # The app container was removed because it's not used for deployment, and local development
  # is often easier with the app running directly on the host machine. If an app container is
  # useful, the PR for the issue that removed it might be a good starting point, see:
  # https://github.com/sul-dlss/earthworks/issues/1037

  db:
    image: postgres:12.8
    environment:
      POSTGRES_USER: earthworks
      POSTGRES_DB: earthworks
      POSTGRES_PASSWORD: earthworks
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  index:
    image: solr:8.11.1
    ports:
      - "8983:8983"
    volumes:
      - index:/var/solr
      - ./config/solr_configs:/solr-setup/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight-core
      - /solr-setup/conf

  cache:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  db:
  index:
  cache:
