# the number of days since a download was last accessed before it is removed from the cache
download_cache_expiry_time_days: 14

# Search engine settings
bing_site_verification: "4E61263975C6ABBF2ECE5A8CA5E592B7"
google_site_verification: "654321sitever"

# Cloudflare turnstile settings for bot challenge page
# NOTE: these example keys always pass the challenge; see:
# https://developers.cloudflare.com/turnstile/troubleshooting/testing/
turnstile:
  enabled: false
  site_key: "1x00000000000000000000AA"
  secret_key: "1x0000000000000000000000000000000AA"
  safelist:
    - 171.64.0.0/14
    - 10.0.0.0/8
    - 172.16.0.0/12

# Turn off in production to store events via google analytics
analytics_debug: true

# Settings for feedback submission form
hostname: "HOST"
email_to: "fake-email@example.com"
recaptcha:
  site_key: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  secret_key: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

# Used to generate canonical links and JSON-LD content in the <head>
host_url: "http://www.example.com"

# New Relic settings
newrelic_app_name: "should be specific to stage and prod"
newrelic_license_key: "this is private"
newrelic_enabled: false

# Server used for background jobs
redis_url: "redis://localhost:6379/"

cors:
  allow_origin_url: "https://embed-stage.stanford.edu"

## Indexing settings

# Solr commit within time in milliseconds
solr_commit_within: 5000

# Should be purl_fetcher_stage or purl_fetcher_prod; determines which queue
# of SDR item updates we are 'listening' to
indexer_topic: purl_fetcher_stage

# Kafka groups split messages across consumers; we don't want to take messages
# from the 'real' stage/prod indexers so we set this to a different value
indexer_group: earthworks-dev-indexer

# Target should always be earthworks since we don't want to receive items
# released to e.g. searchworks
purl_fetcher:
  target: earthworks # case-insensitive ("EarthWorks", "Earthworks", etc.)
  skip_catkey: true # skip indexing if item has a catkey

# Determines the environment that cocina metadata will be fetched from; for
# stage indexing it should be set to staging PURL
purl:
  hostname: purl.stanford.edu

# Enable/disable global alerts
# https://github.com/sul-dlss/global_alerts
global_alert: false

honeybadger:
  check_in_id: ~
