name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - bl8

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Prepare application
        run: bin/rails test:prepare
      - name: Run tests
        run: bundle exec rake ci
